---
language: php

git:
  depth: 1

cache:
  directories:
    - $HOME/.composer
    - vendor

env:
  global:
    - PHP_CS_FIXER_IGNORE_ENV=1

php:
  - 7.1
  - 7.2
  - 7.3

before_script:
  - composer install --dev
  - mkdir -p tests/coverage

script:
  - composer test:cs
  - composer test:unit

after_script:
  - travis_retry composer test:upload
