---
language: php

git:
  depth: 1

cache:
  directories:
    - $HOME/.composer
    - vendor

env:
  global:
    - PHP_CS_FIXER_IGNORE_ENV=1

php:
  - 7.1
  - 7.2
  - 7.3

before_script:
- composer global require phpunit/phpunit:^7 php-coveralls/php-coveralls
- composer install
- wget https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v2.15.1/php-cs-fixer.phar -O php-cs-fixer
- chmod +x ./php-cs-fixer
- mkdir -p tests/coverage

script:
- ./php-cs-fixer fix --dry-run --diff
- phpunit -c phpunit.xml.dist

after_script:
- travis_retry php vendor/bin/php-coveralls -v
